### ISSUE TITLE
External library of JSON schema ui

### ISSUE THREAD

**Issue by puria** [ForkbombEu/signroom#218]
Create a svelte lib to allow to compose JSON.schemas with UI components.
Select/checkbox/input boxes... easy without so much detail.

**Comment by bbtgnn** [comment]
Some references:
- [data source for UI options](https://github.com/json-schema-org/json-schema-spec/blob/main/meta/validation.json)
- [js tool to check the generated schema](https://ajv.js.org/)

**Comment by bbtgnn** [comment]
Closed with https://github.com/dyne/json-schema-builder-svelte
