### ISSUE TITLE
on approve and on reject the auditlog should be filled with the entry <-- important

### ISSUE THREAD

**Issue by puria** [ForkbombEu/signroom#263]

**Comment by bbtgnn** [comment]
@puria  if you mean the `logs` section of the UI panel, it's currently not possible, as it logs only the HTTP requests (as stated in https://github.com/pocketbase/pocketbase/discussions/1179)

If you mean to save the logs in the `logs.db` file, that I think I can do

**Comment by puria** [comment]
Then we have to create a separate collection to show Audit Logs. This is **really important** for policy and legal concerns.

What does the logs.db contains, btw?

**Comment by bbtgnn** [comment]
done with #839
