### ISSUE TITLE
Avoid using commands without checks

### ISSUE THREAD

**Issue by puria** [ForkbombEu/signroom#416]
webapp/package.json there is the assumption that `paraglide-js` is installed in the system.
This should be avoided by using for instance:
1. npx that allows to run commands without having them installed globally
2. or if really neaded should be checked before launch here https://github.com/ForkbombEu/signroom/blob/main/Makefile#L17 where all the dependencies are checked inside the Makefile to be available in the system

**Comment by bbtgnn** [comment]
fixed by #646
