### ISSUE TITLE
Qr copy to clipboard

### ISSUE THREAD

**Issue by puria** [ForkbombEu/signroom#427]
In page `/my/organizations/[orgid]/credential-issuances/[serviceid]`

The copy to clipboard of the QR does not work, says:

```
ReferenceError: ClipboardItem is not defined
    Immutable 5
app.7e449bda.js:5:198
```

**Comment by bbtgnn** [comment]
but...
![download](https://github.com/ForkbombEu/signroom/assets/30571828/6fb41474-1c8b-457b-aff5-8c271b1181cb)

haha
I'm going to add a warning or check if the feature is not available.
Maybe add a download button?

**Comment by puria** [comment]
Yeah seems that works only on Safari/Chrome like it's a webkit thing. So mozilla based browsers and edge are out of the game... maybe the lib you are using have some cross-browser option?

**Comment by bbtgnn** [comment]
We are not using a lib actually, but I can check if one exists

[here](https://stackoverflow.com/questions/66962885/async-clipboard-api-clipboarditem-is-not-defined-reactjs-copy-image-to-clipb) one suggests: https://clipboardjs.com/

**Comment by bbtgnn** [comment]
But I think that this lib won't work with images
Maybe we should just not display the button
