### ISSUE TITLE
When entering URLs of credential issuer and authorization, DO NOT append /credential_issuer and /authz_server anywhere

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/signroom#455]
If I now write the URL of the credential issuer as:

https://issuer1.com

inside signroom, somewhere (!!!), it becomes

https://issuer1.com/credential_issuer

(and the same thing happens for the authorization server, where it appends /authz_server)

This must not happen, i.e. the URL must arrive in the QR code as you write it. 

Screenshot is for reference: check the "credential issuer" and check with the contenct of the QR code

https://gyazo.com/f970d1c784e020e32646a2b0d917dca2

**Comment by puria** [comment]
also I guess just our services have `/path` normally servers are root based like:
`issue.example.org`
and
`auth.server.com:3409`

**Comment by bbtgnn** [comment]
already fixed
