### ISSUE TITLE
UI small fixes

### ISSUE THREAD

**Issue by micolsalomone** [ForkbombEu/signroom#482]
- [x] Fix the issuance flow thumb  <img width="1200" alt="image" src="https://github.com/ForkbombEu/signroom/assets/26438256/9bd8b2b0-4a4d-4477-bf06-4ef6b46194e8">
-----
- [ ] fix the background for selected lists (orgs) in the sidebar
<img width="233" alt="Screenshot 2024-04-10 alle 11 42 13" src="https://github.com/ForkbombEu/signroom/assets/26438256/456ad639-3e57-4108-8b4b-a02e08a80130">
->
<img width="233" alt="sidebar" src="https://github.com/ForkbombEu/signroom/assets/26438256/cad65a33-92d3-419a-a84e-bf889382db13">

**Comment by micolsalomone** [comment]
![Image](https://github.com/ForkbombEu/signroom/assets/26438256/01e8a433-5105-4183-a667-f3e33df39494)

header is missing, use the one without breadcrumbs [[design link](https://www.figma.com/file/pdwfO3dMKtaCAQakht0JE6/DIDRoom-%2B-Signroom---WF-and-GUI---Dyne.org?type=design&node-id=2990%3A4995&mode=design&t=XClMktj9ofLxMeQh-1)]

**Comment by bbtgnn** [comment]
@micolsalomone I won't fix the last one, as it needs a deep refactoring (it's old bad code)
As a temp solution, i just added a card around the table

![Didroom](https://github.com/ForkbombEu/signroom/assets/30571828/0dfaef1b-4da3-4f32-b434-a4eb01406d2e)
