### ISSUE TITLE
Remove microservice public keys (inside "kid") - for each of the 3 microservices

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/signroom#484]
We need to remove to pubkeys hardcoded in: 

Credential Issuer: public/.well-known/openid-credential-issuer 
Authz server: public/.well-known/oauth-authorization-server
Relying party:   public/.well-known/openid-relying-party

We need to **remove the object "kid"**

```
"jwks": {
   "keys": [
      {
	"kid": "did:dyne:sandbox.genericissuer:GPgX3sS1nNp7fgLWvvTSw4jUaEDLuBTNq5eJhvkVD9ER#es256_public_key",
	"crv": "P-256",
	"alg": "ES256",
	"kty": "EC"
	}
    ]
}
```

!!!! Important!!!!  --->  **do NOT match the content, match the key name instead** as the content will change multiple type in the future.

**Comment by jaromil** [comment]
@andrea-dintino very GOOD that we finally clean deeper all hardcoded  stuff
