### ISSUE TITLE
Verification flow templates

### ISSUE THREAD

**Issue by matteo-cristino** [ForkbombEu/signroom#496]
When creating a verification flow I can choose to use also issuance templates in the templates part (`type` equal to `issuance` in pb), but using them it fails to create a new verification flow. do not know if using issuance template is wanted or not, anyway it should be fixed in one or another way

**Comment by andrea-dintino** [comment]
This seems to be fixed already in the latest version (which is about to be deployed) as the problem doesn't occur on my local deployment.
