### ISSUE TITLE
"New Verification Template" button opens the "New issuance template" 

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/signroom#499]
it happens when the user is in the Edit verification flow page

Screenshot: https://gyazo.com/d9af390023437bbe727019d0672d5e12

The buttons to create Auth template e Issuance template, from the Edit Issuance flow work fine

**Comment by bbtgnn** [comment]
@andrea-dintino  Could you provide more details? I tried to replicate but it's not happening
