### ISSUE TITLE
QR code and copy of the verification flow, should have its own logic

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/signroom#500]
Currently the QR code and copy is currently the same as the issuance flow. 

Screenshot: https://gyazo.com/056f091e09f406b656cc8025069acae0

The QR code generation should have and copy should be different

**Comment by andrea-dintino** [comment]
Actually most of the QR code is generated by the verifier app... therefore for now please hid the QR code, and just add some copy saying: 

The QR code for the verification is generated by the DIDroom Verifier app

**Comment by micolsalomone** [comment]
I updated the designs and simplified according to @andrea-dintino instructions.
I also improved the QR cose public HTML page 
for credential QR code
<img width="766" alt="image" src="https://github.com/ForkbombEu/signroom/assets/26438256/00c6802a-28aa-4e1d-a388-405e79cf9b2c">
<img width="766" alt="image" src="https://github.com/ForkbombEu/signroom/assets/26438256/6538cb72-4218-48e4-a8c2-8142df3e40b3">

and for verification flow
<img width="776" alt="image" src="https://github.com/ForkbombEu/signroom/assets/26438256/703d9999-3682-4660-94ac-4e6be09bcfc8">
