### ISSUE TITLE
Add last issuance flows in [org]/Home

### ISSUE THREAD

**Issue by micolsalomone** [ForkbombEu/signroom#514]
https://www.figma.com/file/pdwfO3dMKtaCAQakht0JE6/DIDRoom-%2B-Signroom---WF-and-GUI---Dyne.org?type=design&node-id=3409%3A41964&mode=design&t=XClMktj9ofLxMeQh-1

![Image](https://github.com/ForkbombEu/signroom/assets/26438256/8586a450-89f8-4e2d-b005-feb7fc9a35ef)

**Comment by bbtgnn** [comment]
@micolsalomone has some requests!

**Comment by bbtgnn** [comment]
Updates here:
https://www.figma.com/file/pdwfO3dMKtaCAQakht0JE6/DIDRoom-%2B-Signroom---WF-and-GUI---Dyne.org?type=design&node-id=3869-51024&mode=design&t=CdDO7zuwXs081LYq-4
