### ISSUE TITLE
Add trusted credential issuer when creating a verfication flow

### ISSUE THREAD

**Issue by matteo-cristino** [ForkbombEu/signroom#536]

**Comment by matteo-cristino** [comment]
@andrea-dintino should we add all credential issuer or let the user select the one he/she want? The truste credential issuer array will be added in the relying party well known at the end

**Comment by matteo-cristino** [comment]
Add all public and under the same organization credential issuer

**Comment by bbtgnn** [comment]
superseeded by #507
