### ISSUE TITLE
Visibility for simple "members" of the org

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/signroom#539]
When logged as member of the org: 

- in Members: remove the "edit role" button
- in the "view issuance" flow page  remove the "download issuer" button
- in the "view" flow page (both issuance and verification), remove the "make changes" button
- Templates and microservices must be hidden

**Comment by bbtgnn** [comment]
@andrea-dintino  about point 2 and 3
code that hides them is already in place
the issue arises in the deployment or also locally?
