### ISSUE TITLE
Dropdown to change the locale (language)

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/signroom#541]
There should be a way to change locale. Not in the settings, but better in the top right of the page.

**Comment by puria** [comment]
i do not rememeber where is the name of the user and the avatar, but should be, very close to that! when you find your name and picture, is where your language should also be visible ❤️‍🔥

**Comment by bbtgnn** [comment]
@puria currently we have this
<img width="267" alt="Screenshot 2024-04-19 alle 07 42 32" src="https://github.com/ForkbombEu/signroom/assets/30571828/405cc5ac-f199-463a-ab37-b5b58e757edc">

Should we put it above the username?
