### ISSUE TITLE
Make software version visible somewhere in the webapp

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/signroom#557]
Somewhere in the webapp the version should be visible. The commit number will be enough. Not sure where to show it, I leave this to @bbtgnn

**Comment by puria** [comment]
It's already in the console log but not managed (read inside the package.json version):
 - [ ] Add semantic-release
 - [ ] Add semantic-release/npm and github to increase the release number
 - [ ] Show the version/sha in the GUI

**Comment by bbtgnn** [comment]
closed by #617
