### ISSUE TITLE
Update microservice download

### ISSUE THREAD

**Issue by matteo-cristino** [ForkbombEu/signroom#719]
Since the new version of DIDRoom_microservices to have easier deploy the following is needed:
* Add to the .env.example `MS_NAME` with the name of the service, *e.g.* `MS_NAME=dev_credential_issuer`
* Add to the .env.example `MS_URL` with the url of the service, *e.g.* `MS_URL=https://dev.issuer1.forkbomb.eu/credential_issuer`
* If it possible copy the permission of file under the `scripts/` folder otherwise let me know and I will handle it from makefile

**Comment by puria** [comment]
with .zip files AFAIK permissions are lost. `.tar.gz` can keep them. But `.zip` is better for cross-os interoperability (the day that ncr will run under windows, shell scripts should work under WSL I guess). Anyhow maybe also .tar.gz is already supported in WSL, no?

All this to say that... yes just put it exlpicit in the makefile ;p

**Comment by matteo-cristino** [comment]
file permission handling is now done from DIDRoom_microservices Makefile.

MS_NAME and MS_URL are set as empty in the .env.example at this moment. Moreover a check over there value is done and if empty throw to the user the error:
```
Set MS_NAME and MS_URL in .env respectively to the name of this folder and the url of the service
```
So that until signroom will handle this correctly the user is told what he needs to do.

**Comment by bbtgnn** [comment]
Are there any are the updates on this? What do I have to do?

**Comment by puria** [comment]
Involve @andrea-dintino on suggestions on how to insert the variables from the frontend **if missing**. If nothing is needed, from his perspective. Then nothing has to be done ;*

**Comment by andrea-dintino** [comment]
Ok, @puria and myself talked about the issue, we think:

1) Port: 
- add a field for the port, 
- the port is auto-populated based on a logic (looking for a range of typically unused ports, above port 1024 as no root access is needed) 
- the port number is displayed in the Microservice part of the dashboard

2) Add a warning when the user wants to save/modify the **name** OR the **endpoint** of any microservice, saying: 

**Are you sure?** 
The name, the enpoint and the port, define the identity of the microservice and have effect on the the deployment and the update. Once a microservice is deployed and initialized, we recommend not change name, endpoint or port

3) after this is done, for each microservice then, the dashboard **should create a .env file for each microservice** and place it in the microservice folder, the file should look like: 

# Leave empty
FILES_DIR=.     

# Don't change, unless you have something else running on port 8000
ANN_PORT=8000  

# The microservice will run on this port 
UP_PORT= {port_from_dashboard}

# This is the microservice folder, populated by the DIDroom dashboard, from the microservice name 
MS_NAME= {name from dashboard slugify } 

# This is the microservice endpoiny, populated by by the DIDroom dashboard
MS_URL= {endpoiny from dashboard  }
