### ISSUE TITLE
Design responsive email templates for each scenario listed above.

### ISSUE THREAD

**Issue by puria** [ForkbombEu/signroom#773]

**Comment by micolsalomone** [comment]
HTMLs here: https://cloud.dyne.org/s/ByprjMRQwtYfDsY

**Comment by micolsalomone** [comment]
There are some conditions that apply when an Issuance flow is updated. The email content should be changed based on those conditions.

1. If only the flow name is updated:
- Send an email notifying only about the flow name update.
2. If only the encryption or expiration is updated:
- Send an email focused on changes related to encryption or expiration date.
3. If only the authorization or credential template is updated:
- Notify about changes in the authorization or credential template, focusing only on these changes.
4. If only the microservices (Authorization Server or Credential Issuer) are updated:
- Dedicated email for microservice updates.
5. If only the advanced settings (visibility or API access) are updated:
- Send a specific email for these updates.
6. If multiple attributes are updated at the same time:
- Combine the relevant information in an email that summarizes all the changes made

**Comment by puria** [comment]
Well done! I've just rendered them! I'll make a PR to the repo now.

I think that the welcome emails, maybe need some more guidance and info (maybe a link to a video) or some material that explains the capability of the platform, more marketing material.

But we can add them iteratively!
I mark for now this task done!

Thanks!
