### ISSUE TITLE
In the Issuance flow creation, remove the default field under "Attributes needed *

### ISSUE THREAD

**Issue by andrea-dintino** [ForkbombEu/signroom#776]
Here:

https://gyazo.com/810eae262e4cd9ff59a85d3b6a027a4f

The auto-filled "DID" must be removed, as it causes issues right now. We should consider to remove this section at once

**Comment by bbtgnn** [comment]
@andrea-dintino I cannot reproduce. The auto-filled "did" appears only if you select a preset, not in other cases. Could you elaborate further?

**Comment by andrea-dintino** [comment]
> @andrea-dintino I cannot reproduce. The auto-filled "did" appears only if you select a preset, not in other cases. Could you elaborate further?

That is correct - please disable that whole section as it's not clear if and how we'll use it.
