### ISSUE TITLE
JSON Schema parser is too strict with fields not supported by standard JSON Schema

### ISSUE THREAD

**Issue by matteo-cristino** [ForkbombEu/signroom#938]
The strict adherence to the JSON Schema standard in the authorization page prevents us from using some extra fields that are supported by JSONEditor (that is the only one that uses that JSON schema).

Example:
To have a multiple choice questionnaire like
![Image](https://github.com/user-attachments/assets/49ee876a-5ddf-4f42-9c28-2caa84727442)

with JSONEditor I can use the following schema:
```json
{
   "type":"object",
   "properties":{
      "voucher":{
         "type":"number",
         "title":"voucher discount percentage",
         "enum":[
            10,
            20,
            30,
            40,
            50,
            100
         ],
         "options":{
            "enum_titles":[
               "10%",
               "20%",
               "30%",
               "40%",
               "50%",
               "100%"
            ]
         },
         "format":"radio"
      }
   },
   "required":[
      "voucher"
   ]
}
```
but `options` (used here to specify the string to show) and `"format":"radio"` (used to specify the multiple choice format) are not supported by standard json schema

**Comment by bbtgnn** [comment]
@matteo-cristino I did some tests. This issue depends on Json Schema Validation being set on 'strict' mode.
If we remove the 'strict' mode we have no errors, but then we don't catch errors on other important fields, like "type".

What should we do? Shall we allow only the extra keywords requested by JSONEditor?
